### ISSUE TITLE
Display "reply-to" addresses of received emails on suggest contacts

### ISSUE THREAD

**Issue by lqust** [pixelated-project/pixelated-user-agent#173]

**Comment by shyba** [comment]
Done and on my stash, but I stumble up on #256 during the tests and it isn't reliable. As soon as the tests are fixed this will go ahead.

**Comment by dudadornelles** [comment]
I sent an email from an external account to my pixelated one and it works. However, when I see the contact in the autocomplete, I only see its name, not the email.

![screen shot 2015-01-29 at 10 42 28 am](https://cloud.githubusercontent.com/assets/249770/5957673/828397b8-a7a3-11e4-9088-22878eb0f279.png)

@lqust says that we would like to see "Name <email>" there

If it is an easy fix let's just do it in this card otherwise we will create a new one and close this.

What you say @shyba

**Comment by dudadornelles** [comment]
There is another detail - this is the 'from' address and not the 'reply_to' field that could be added.

For instance, I could send an email like:

"
From: Duda Dornelles <duda@pixelated-project.org>
Reply-To: <duda@personalemail.com>
"

In this case we want both contacts in the contacts list, correct @lqust ?

**Comment by shyba** [comment]
Yep! Its a bug!
Will try to reproduce and fix. It looks like something with indexing/searching from the sender field.

The other detail I guess its up to @lqust , I dont see a problem on indexing and searching from both fields and can make it work like this.

**Comment by shyba** [comment]
Related to #233 , email tag is being interpreted as html. 
I am working on it and will discuss some options to avoid this in the future. We may need to escape all by default (discussed earlier with @bwgpro and will create issues and discussions for that).

**Comment by shyba** [comment]
@dudadornelles XSS fixed thanks to patch from @kaofelix .
