### ISSUE TITLE
tell user if mails are not synced yet

### ISSUE THREAD

**Issue by cz8s** [pixelated-project/pixelated-user-agent#219]
the initial soledad sync takes very long if there are already
mails in the database. 
Until the database is fully synced the webinterface does not show any mails. We should display a status until
soledad is synced.

**Comment by dudadornelles** [comment]
There is already a feature for that but we probably need to improve. Right now, when mails are being synced to soledad, you'll see an orange progress bar on top of the mail list. It disappears when the mails are synced. The problem is that, after that, they must be indexed into the search engine, and the progress bar is ignoring that overhead right now.

**Comment by lqust** [comment]
progress bar was removed

**Comment by bwgpro** [comment]
Was this solved by the loading screen? @cz8s

**Comment by cz8s** [comment]
Think so, yes
